install: gradle wrapper --gradle-version 4.2
language: java
+jdk: oraclejdk8
sudo: true
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  artifacts:
    target_paths:
    - /
    paths:
    - /home/travis/build/Sweex99/DreamTeam/build/libs/DreamTeam-1.0-SNAPSHOT.jar