install: gradle wrapper --gradle-version 4.2
language: java
+jdk: oraclejdk8
sudo: true
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  artifacts:
    paths:
    - $HOME/build/Sweex99/DreamTeam/build/libs/*.jar
    target_paths:
    - /$TRAVIS_OS_NAME