install: gradle wrapper --gradle-version 4.2
language: java
+jdk: oraclejdk9
sudo: true
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  artifacts:
    target_paths:
    - /artifacts
    paths:
    - $(ls $HOME/build/Sweex99/DreamTeam/build/libs | tr "\n" ":")